type: postgres
name: webinardb
connection:
  host: ${env.POSTGRES_HOST}
  port: ${env.POSTGRES_PORT}
  database: ${env.POSTGRES_DATABASE}
  user: ${env.POSTGRES_USER}
  password: ${env.POSTGRES_PASSWORD}

